### ISSUE TITLE
Написать оформленное ТЗ

### ISSUE THREAD

**Issue by V1zefull** [V1zefull/Grand-Gym#2]

**Comment by V1zefull** [comment]
**1.ТЕХНИЧЕСКОЕ ЗАДАНИЕ**
---------------------------------------------------------------------------------------------------------------
**1.1.Общие сведения**
---------------------------------------------------------------------------------------------------------------
**1.1.1.Полное наименование системы**
Веб приложение - сайт для покупки абонемента в фитнес зал

**1.1.2.Плановые сроки начала и окончания работы по созданию системы**
Начало работы: 01.09.2022

Окончание работы: 01.12.2022
---------------------------------------------------------------------------------------------------------------
**1.2.Назначение и цели создания (развития) системы**
---------------------------------------------------------------------------------------------------------------
**1.2.1.Назначение системы**
Назначением системы является возможность получения клиентом услуг предоставляемы фитнес залом.

**1.2.2.Цели создания системы**
Цель создания системы –  Помощь в работе как клиентов так и рабочего персонала фитнес зала, путём формирования приложения со всем необходимым функционалом для работы которая ранее выполнялась через менеджеров в офисе.

**1.3.Характеристики объекта автоматизации**
---------------------------------------------------------------------------------------------------------------

Объектом автоматизации является процесс предоставления услуг. Автоматизированию подлежит отслеживание статусов предоставленных услуг(действует та или иная услуга на данный момент или она заморожена и тд). Клиент выбирает понравившуюся услугу из предложенного каталога услуг и добавляет его в профиль. Клиент оформляет услугу, указывая данные для связи. После того как услуга будет обработана, клиент сможет ей в фитнес центре.

**1.4.Требования к системе**
---------------------------------------------------------------------------------------------------------------

**1.4.1.Требования к системе в целом**
Программный продукт должен представлять собой сервис, включающий в себя серверную часть и веб-приложение.

**1.4.2.Требования к структуре и функционированию системы**
Приложение должно быть разделено на 4 слоя:

* Слой клиентского приложения в виде веб-приложения ;
* Слой бизнес-логики приложения (сервер); 
* Слой администраторской части
* Слой хранения данных (база данных).

Функционал приложения должен содержать:
* Возможность оформления заявки о приобретении услуг фитнес зала
* Отслеживания статуса действия предоставляемых залом услуг
* Возможность для работников фитнес зала контролировать состав спорт инвентаря, добавлять новые типы услуг и 
типы тренажёров

**1.4.3.Требования к надежности**
Система должна обеспечивать корректную обработку исключительных ситуаций, вызванных, например, вводом неверных пользовательских данных или неоднозначной информации в базу данных. Сохранность личных данных пользователей.

** 1.5.Состав и содержание работ по созданию системы **
---------------------------------------------------------------------------------------------------------------
|Стадии      | Этапы работы             | Сроки выполнения|
| ------------- |:------------------:| -----:|
| 1. Формирование требований к АС |1.1. Исследование объекта и подтверждение необходимости создания АС. 1.2. Формирование требований пользователя к АС. 1.3. Оформление отчёта о выполненной работе и заявки на разработку АС.  |  |
|2. Разработка концепции АС. | 2.1. Изучение выбранного объекта. 2.2. Проведение научно- исследовательских работ. 2.3. Проектирования концепции АС, удовлетворяющей потребности пользователя. 2.4. Оформление отчёта о выполненной работе. |   |
| 3. Техническое задание. | Разработка и утверждение технического задания на создание АС. |  |
| 4. Разработка системы. | Разработка системы согласно техническому заданию. |  |
| 5. Защита курсовой работы. | 5.1. Создание грамотной презентации и речи для защиты курсовой работы. . Защита курсовой работы. |  |

** 1.6.Порядок контроля и приемки системы **
---------------------------------------------------------------------------------------------------------------
** 1.6.1.Состав, объем и методы испытаний системы и ее составных частей **
Приложение должно пройти предварительные испытания, состоящие из отладки и минимального набора тестов.

В результате предварительных испытаний, должны быть исправлены недочеты, замечания на которые были получены в ходе предварительных испытаний.

Для проверки корректной работы внесённых изменений должны быть проведены повторные испытания разработанной системы.

** 1.6.2.Общие требования к приемке работ **
В процессе приемки работ должна быть осуществлена проверка на соответствие требованиям настоящего «Технического задания». По результатам испытаний возможны доработки и исправления.

1.7.Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие
---------------------------------------------------------------------------------------------------------------
При подготовке объекта автоматизации к вводу системы в действие следует выполнить:

* Обеспечение работ по вводу данных в систему;
* Развертывание системы на сервере;
* Настройка системы доступа и создание учетных записей.

** 1.8.Требования к документированию **
---------------------------------------------------------------------------------------------------------------
По окончанию работы предъявлена расчетно-пояснительная записка, в состав которой входят:

Техническое задание;
Научно-исследовательская часть;
Проектно-конструкторская часть;
Проектно-технологическая часть.
Также должна быть предоставлена графическая часть работы, выполненная в формате А1 на 2 листах, в которую входят:

Демонстрационные чертежи;
Алгоритмические схемы.

** 1.9.Источники разработки **
---------------------------------------------------------------------------------------------------------------
• Гост 34.601-90;

• Гост 34.602-89.

**Comment by wldmr-key** [comment]
Основная проблема - из ТЗ не видно, насколько сложным будет приложениеи с каким объемом данных оно будет работать. Поэтому в таком виде утвердить его не могу. Как минимум, следует более подробно и понятно расписать функции приложения

> Назначением системы является помощь в получения услуг спортивного зала.

Помощь кому? Каких услуг? Кто будет пользоваться этой системой?

> Цель - Получение услуг покупки абонементов, отслеживания статусов различных услуг предлагаемые спорт залом

В чьих интересах создается система? В чем заключается этот интерес?

> Объектом автоматизации является веб-приложение. 

То есть, существует какое-то неавтоматизированное веб-приложение и ты мечтаешь его автоматизировать? Так?

> Автоматизированию подлежит отслеживание необходимой информации для пользователя.

То есть ты хочешь избавить пользователя (кстати, опять, кто это?) от отслеживания необходимой для него информации? Если от ее отслеживания можно избавиться - так ли она необходима? ))

> Функционал приложения должен содержать:

что такое покупка? абонементов бесконечное количество? они одинаковые?
что такое статус?
что за дополнительные услуги?
что такое администрирование?

**Comment by V1zefull** [comment]
Переработал тз по сделанным замечаниям, постарался всё исправить

**Comment by wldmr-key** [comment]
в назначении можно не перечислять функции, достаточно указания тех, кто будет системой пользоваться
цель - "облегчение" лучше переформулировать

опять "Объектом автоматизации является веб-приложение"! объектом автоматизации является процесс предоставления услуг

в функциях нет покупки, нет работы с индивидуальными тренерами, нет расписания

**Comment by V1zefull** [comment]
Постарался исправить все недочёты

**Comment by wldmr-key** [comment]
значительно лучше. Берем ))
