### ISSUE TITLE
Написать предварительное описание предметной области и требований к системе

### ISSUE THREAD

**Issue by V1zefull** [V1zefull/Grand-Gym#3]

**Comment by V1zefull** [comment]
**Требования к структуре и функционированию системы.**

**Система представляет из себя несколько модулей:**

Программный продукт должен представлять собой сервис, включающий в себя серверную часть и веб-приложение.

Приложение должно быть разделено на 4 слоя:

- Слой клиентского приложения в виде веб-приложения. В этом слое клиенты смогут посмотреть информации о компании, ознакомиться со списком услуг и их ценами, зарегистрироваться и оформить услугу. Система должна предоставлять клиенту страницу выбора услуги с сортировкой по типам. Пользователь может регистрироваться в системе (а также авторизовываться после регистрации)

- Слой бизнес-логики приложения. Слой, на котором описывается основной функционал взаимодействия с клиентской и серверной частью

- Слой администраторской часть, где администраторы смогут добавлять услуги и категории услуг, а также просматривать список тренажёров и добавлять их.

Функционал приложения должен содержать:

- Возможность оформления заявки о приобретении услуг фитнес зала
- Отслеживания статуса действия предоставляемых залом услуг
- Возможность для работников фитнес зала контролировать состав спорт инвентаря, добавлять новые типы услуг и типы тренажёров

**Требования к надежности.**

Система должна обеспечивать корректную обработку исключительных ситуаций, вызванных, например, вводом неверных пользовательских данных или неоднозначной информации в базу данных. Сохранность личных данных пользователей.

**Описание предметной области**
В данном курсовом проекте была описана деятельность интернет-сайта по предоставлению услуг фитнес центра. Интернет-сайт позволяет пользователям онлайн выбрать услугу, которая присутствует на сайте, сформировать запрос на оформление. Управления интернет-сайтом – это процесс планирования, координации и контроля бизнес-процессов в интернет-сайте. Администратор является главным звеном в бизнес-процессе, который должен поддерживать актуальную базу данных о наличии услуги, для большого спроса клиентов.
В созданном мною интернет-сайте существует две роли: клиент(заказчик) и администратор.

У клиента есть возможность выбора товара из каталога. Упрощает данный выбор сортировка на типы. Под типами подразумеваются какие виды услуг есть.
Также у услуг могут быть свойства, которые могут описывать возможности предоставляемой услуги, характеристики или любую другую информацию.
Покупатель выбирает услугу и делает запрос на оформление. На данном этапе пользователь должен быть авторизован. После формирования заявки на оказание услуги, пользователь оформляет заявку: заполняет данные для связи.

После оформления заявки с заказчиком связываются для уточнения деталей заказа. Пользователь может посмотреть список своих выбранных услуг в личном кабинете.

**Comment by wldmr-key** [comment]
Описание предметной области ты с чем-то перепутал. Предметная область - это деятельность спортзала, а не интернет магазина. То, что у тебя, скорее, может быть перенесено в требования к приложению.
Требования к системе у тебя не совпадают с ТЗ

**Comment by V1zefull** [comment]
Изменил требования к структуре согласно написанному ТЗ 
**Требования к структуре и функционированию системы.**

**Система представляет из себя несколько модулей:**

Программный продукт должен представлять собой сервис, включающий в себя серверную часть и веб-приложение.

Приложение должно быть разделено на 3 слоя:

- Слой клиентского приложения в виде веб-приложения. В этом слое клиенты смогут посмотреть информации о компании, ознакомиться со списком услуг и их ценами, зарегистрироваться и оформить заявку, после чего видеть свою заявку в личном кабинете. Система должна предоставлять клиенту страницу выбора услуги с сортировкой по типам. Пользователь может регистрироваться в системе (а также авторизовываться после регистрации)

- Слой бизнес-логики приложения. В этом слое описывается функционал менеджера который занимается рассмотрением полученных заявок и обзвоном клиентов

- Слой администраторской часть, где администраторы смогут добавлять услуги, типы услуг категории услуг, изменять их. Администратор так же добавляет и изменяет всё что связано с тренажёрами.

Функционал приложения должен содержать:
- Формирование заявки о приобретении услуг фитнес центра
- Обработка заявки о приобретении услуг фитнес центра
- Отслеживания заявки предоставляемых залом услуг, как для клиента так и для менеджера
- Контроль состава спорт инвентаря для работников фитнес центра. 
- Добавление новы типов услуг 
- Добавление услуг 
- Добавление брендов тренажёров 
- Добавление типов тренажёров
- Добавление тренажёров
- Изменение информации о тренажёрах
- Изменение информации об услугах

**Требования к надежности.**

Система должна обеспечивать корректную обработку исключительных ситуаций, вызванных, например, вводом неверных пользовательских данных или неоднозначной информации в базу данных. Сохранность личных данных пользователей.

**Comment by V1zefull** [comment]
По поводу предметной области я не совсем понял что от меня требуется, объясните пожалуйста поподробнее

**Comment by V1zefull** [comment]
Обновил требования к системе

**Comment by V1zefull** [comment]
**Описание предметной области**
В данном курсовом проекте была описана деятельность фитнес центра. Фитнес центр предоставляет клиентам выбрать интересующею их услугу разных типов, на пример услуга покупки абонемента или услуга персонального тренера. Фитнес центр обрабатывает заявки на предоставление услуг путём обзвона клиентов и предоставления им информации об услугах интересующие клиента, сбору информации о данных пользователя  для формирования договора, назначения даты и времени, когда необходимо прибыть клиенту для подписания договора. Так же фитнес центр предоставляет доступ ко множеству тренажёров разных брендов и типов, наличие и информация о которых может интересовать клиента.  Управление фитнес центром – это процесс планирования, координации и контроля процессов предоставления услуг, информации об услугах, информации о тренажёрах которыми владеет центр, оформления и заключения договоров по оказанию услуг предоставляемы фитнес центром. Менеджер является главным звеном в координации и контроля процессов, который должен работать с клиентами путём предоставления всей информации об услугах, тренажёрах, он так же должен рассматривать заявки оставленные клиентом, формировать и заключать договоры о предоставлении услуг фитнес центра.
В качестве автоматизации будет использоваться приложение с уже заранее предоставленной информацией об услугах и тренажёрах которые интересуют клиента, так же автоматизации подлежит оставление заявки от клиента на оказание услуг предоставляемые фитнес центром, данные о которой может просмотреть менеджер и одобрить заявки.

**Comment by V1zefull** [comment]
Обновил описание предметной области

**Comment by wldmr-key** [comment]
Еще раз: предметная область - это то, что существовало, существует и будет существовать и без твоего приложения. Ты пишешь: "интернет-сайт" (ох!). Он уже есть? Его кто-то написал? И он работает уже, как ты описал? Зачем, тогда, твое приложение? Я хорошо объяснил?

Требования к системе:

> Приложение должно быть разделено на 4 слоя:

я насчитал три

> Функционал приложения должен содержать:

маловато получается. Ты в разных местах перечисляешь гораздо больше функций. Собери их все вместе! И, пожалуйста, не употребялй слово "возможость": возможность дает лотерейный билет.

**Comment by V1zefull** [comment]
Концептуальная схема
![image](https://user-images.githubusercontent.com/44523651/208527203-a763dac2-45a2-45f5-ac5b-6cf0ff398ce8.png)

**Comment by V1zefull** [comment]
Исправил описание предметной области, но мне кажется оно вышло очень коротким

**Comment by V1zefull** [comment]
Добавил функционала

**Comment by wldmr-key** [comment]
Предметная область - нет ничего о тренажерах, поэтому, непонято, зачем нужнгы какие-то функции от системы, кто этой информацией будет пользоваться и зачем. Общие слова про "необходимую информацию" (какую?!) и прочие бизнес-процессы следует выбросить и написать о деятельности центра по существу - что он делает и сделать вывод о том, какие действия можно автоматизироать и зачем. Что такое тип услуги и часть других слов концептуальной схемы так же нигде не расшифровано

**Comment by V1zefull** [comment]
Обновил описание предметной области

**Comment by wldmr-key** [comment]
)) я думал фитнес-центр все больше фитнесом занимается, а он вон как... ))

Но, знаешь, такая точка зрения тоже имеет право на существование. То есть, цель разработки - автоматизация деятельности менеджера и предоставление информации об услугах зала клиентам. ок. С персональными тренерами в описании все хорошо, а в списке требований и далее они уже отсутствуют. Времени на это уже не хватит, поэтому, можно перекатить на следующий этап, думаю

Если сможешь, постарайся изложить свое описание более русским языком
