### ISSUE TITLE
Выполнить предварительный анализ аналогов

### ISSUE THREAD

**Issue by V1zefull** [V1zefull/Grand-Gym#4]

**Comment by V1zefull** [comment]
Аналогами разрабатываемого проекта можно назвать сайты других фитнес-центров.
Сайт Фитнес-центра Grand Fitness — сайт разработанный для фитнес центра Grand Fitness.

* На сайте клиент имеет возможность выбора адреса фитнес зала
![image](https://user-images.githubusercontent.com/44523651/200818624-1a995eae-48a6-4aa1-921a-28f70ef7d9a1.png)

* Список классов для групповых занятий
![image](https://user-images.githubusercontent.com/44523651/200818794-5082b8f4-ee30-4f7c-8fd3-b64791e809c2.png)

* Так же имеется просмотр расписания общих мероприятий проводимых в фитнес центре
![image](https://user-images.githubusercontent.com/44523651/200819053-40bbdcca-365d-4738-bc5d-2f01e5494d64.png)


* Просмотра списка услуг и оставления заявки на консультацию с менеджером. 
![image](https://user-images.githubusercontent.com/44523651/200818942-05bc18ae-871f-4f2f-b38f-94ad78f53300.png)
![image](https://user-images.githubusercontent.com/44523651/200819167-fdf32b2d-3f8b-4e98-8c02-0c17471e2b0d.png)

Имеется личный кабинет доступ к которому предоставляет менеджер отдела продаж.
Задача данного сайта является предоставлением необходимой информации для ознакомления с услугами предоставляемые фитнес центром


* Также похожую систему имеет фитнес центр JoyFit.
![image](https://user-images.githubusercontent.com/44523651/200819480-78fe296c-6375-4560-b546-6623e8df5524.png)
![image](https://user-images.githubusercontent.com/44523651/200819600-0d55f838-f2b7-46f4-9d16-f61f355d8ef5.png)

Отличительной особенностью от Grand Fintess это более обширный спектр услуг который можно посмотреть прямиком на сайте, заказ и оплата выбранных услуг онлайн без необходимости ехать прямиком в центр для консультации с менеджером.
![image](https://user-images.githubusercontent.com/44523651/200819746-95021abd-b186-4905-a5f4-e51f5321607b.png)
![image](https://user-images.githubusercontent.com/44523651/200819787-e21a1a22-ebcc-44ed-a1e3-d72c2414f043.png)
![image](https://user-images.githubusercontent.com/44523651/200819909-b754236b-d1fe-43e5-b727-4bb5b8039c2a.png)

* Так же имеется возможность зарегистрироваться на сайте но для этого необходимо иметь индивидуальный номер членства клуба который даётся в отделе продаж при покупке абонемента 
![image](https://user-images.githubusercontent.com/44523651/200820273-fa266045-bfc3-4426-b9b8-81d22b64912f.png)

* Удобное мобильное приложение позволяющее получать доступ к личному кабинету в любом месте и в любое время
![image](https://user-images.githubusercontent.com/44523651/200820339-36f1fc26-d805-4449-b08a-5cfea4dcb30a.png)

**Comment by wldmr-key** [comment]
Желательно больше подробностей и включить скриншоты и ссылки в пояснительную записку. И, да, фитнесс-центры можно посмотреть и покруче ))

**Comment by V1zefull** [comment]
К сожалению доступа к личным кабинетам у меня нет и внешний вид я не смогу показать

**Comment by wldmr-key** [comment]
а зарегистрироваться не?

**Comment by V1zefull** [comment]
Для того что бы зарегистрироваться в joyfit необходимо знать номер клубной карты но я не состою в клубе
в Grand fitnes я могу получить доступ так как состою там

**Comment by V1zefull** [comment]
Наверное лучшим выбором будет как-то по другому описать личные кабинеты

**Comment by V1zefull** [comment]
Я считаю что в моём проекте это можно описать как + тк у моего проекта будет возможность регистрации без необходимости состояния в клубе

**Comment by V1zefull** [comment]
Поменял данную строку
"* Так же имеется возможность зарегистрироваться на сайте но для этого необходимо иметь индивидуальный номер членства клуба который даётся в отделе продаж при покупке абонемента " думаю так будет корректнее

**Comment by wldmr-key** [comment]
ок пусть будет
