### ISSUE TITLE
Создать концептуальную схему данных предметной области

### ISSUE THREAD

**Issue by V1zefull** [V1zefull/Grand-Gym#5]

**Comment by V1zefull** [comment]
![image](https://user-images.githubusercontent.com/44523651/204024247-3aea6a1f-f6b1-446e-bd77-375405628129.png)

**Comment by wldmr-key** [comment]
о, нет!!!
Концептуальная схема данных - это не одолжение для комиссии при защите, а формализация описания предметной области и требований к системе. У тебя таковых пока не появмлось, поэтому, и результат пока плачевный ((

**Comment by V1zefull** [comment]
![image](https://user-images.githubusercontent.com/44523651/206203280-9eba37dc-7d61-4bb7-8626-22c8dbf38587.png)
Исправленная логическая схема

**Comment by V1zefull** [comment]
Верхняя часть, пользователь и услуги
Нижняя часть тренажёры и бренды
Если под пользователем входит админ то он может добавлять удалять и изменять данные о тренажёрах

**Comment by wldmr-key** [comment]
я ничего не могу сказать о логической схеме, пока не пойму, к чему она прилагается. Уже то, что она состоит из двух изолированнных частей весьма подозрительно

**Comment by V1zefull** [comment]
![image](https://user-images.githubusercontent.com/44523651/207022366-ed9f43ee-f894-4417-ab06-78d1d3a29b3e.png)
Отредактировал немного схему
То что она состоит из двух изолированных частей это потому что часть trainer это тренажёры и их видит лишь админ и он может их добавлять и в идеале удалять

**Comment by V1zefull** [comment]
А первая часть это зависимости клиента и услуг, клиент может приобрести услугу

**Comment by wldmr-key** [comment]
вот здесь - https://github.com/V1zefull/Grand-Gym/issues/3 - пусто. Концептуальной схемы - нет. Как я могу оценить правильность логической?!
