### ISSUE TITLE
Изготовить прототип или скетчи пользовательского интерфейса

### ISSUE THREAD

**Issue by V1zefull** [V1zefull/Grand-Gym#6]

**Comment by V1zefull** [comment]
![image](https://user-images.githubusercontent.com/44523651/197185062-07222c27-1fc7-4ff8-8228-89dd0d9bd1d9.png)
Главная страница на которую пользователь попадает заходя, пользователь находится в незарегистрированном состоянии

**Comment by V1zefull** [comment]
![image](https://user-images.githubusercontent.com/44523651/197395906-b15fd5ed-ab59-4492-9108-30c0a4d9c133.png)
Страница входа в аккаунт

**Comment by V1zefull** [comment]
![image](https://user-images.githubusercontent.com/44523651/197395731-8affa4bf-c509-489d-ac5f-a56b0e4b142b.png)
Страница регистрации аккаунта

**Comment by wldmr-key** [comment]
с точки зрения дизайна - прекрасно
с точки зрения функционала - пока нерепрезентативно

**Comment by V1zefull** [comment]
![image](https://user-images.githubusercontent.com/44523651/197778727-6a4c7dda-7b84-481c-8ba4-e1b68bc0015a.png)
Страница клиента с отображением предоставленных услуг, что входит в данные услуги и их статус
Кнопка в виде календаря открывает расписание занятий для каждого клиента индивидуально
Кнопка в виде снежинки замораживает услугу на 1 месяц
Кнопка в виде креста принудительно завершает срок действия услуги

**Comment by V1zefull** [comment]
![image](https://user-images.githubusercontent.com/44523651/197786124-9d09de6a-9a48-4a38-acb4-56dcabfe2944.png)
Страница с перечислением услуг предоставляемые фитнес залом
Каждая иконка услуги это отдельная друг от друга услуга

**Comment by V1zefull** [comment]
![image](https://user-images.githubusercontent.com/44523651/197821447-14ac0375-f8de-4cc2-b73f-0d2bb3981945.png)
Страница сотрудница фитнес-центра со списком клиентов которые привязаны к тренеру и статусом оплаты услуги
Так же в аккаунте сотрудника вместо вкладки services  появилась вкладка inventor, переводящая на страницу со списком спорт инвентаря

**Comment by wldmr-key** [comment]
все хорошо, но мне пока не видно, откуда в системе данные появляются/изменяются

**Comment by V1zefull** [comment]
![image](https://user-images.githubusercontent.com/44523651/198880142-cfb0672a-e2f0-49ae-aeaa-60402a5e737b.png)
Страница спорт инвентаря доступная для сотрудников фитнес центра при нажатии на один из тренажёров будет открываться карточка со статистикой для этого тренажёра

**Comment by V1zefull** [comment]
![image](https://user-images.githubusercontent.com/44523651/198881396-27233514-2a03-487b-9208-2851d3fe1291.png)
Карточка тренажёра с общим количеством и индивидуальными номерами за которыми прикреплён каждый тренажёр.
нажав на индивидуальный номер можно будет посмотреть состояние определенного тренажёра.
При нажатии кнопки + будет открываться форма добавления нового тренажёра она будет похожа с формой изменения параметров

**Comment by V1zefull** [comment]
![image](https://user-images.githubusercontent.com/44523651/198883365-b8273dac-ac9f-472f-a57a-c5dba453c1cd.png)

Карточка описания конкретного тренажёра на данный момент времени, Задумка в том что бы сотрудниг в случае обнаружения поломки или каких либо замечаний для данного тренажёра записывал их в область для заметок а в строку "Замечания о неисправностях" исправлеля на "Да" что значит есть замечания, в последствии при исправлении неисправности данные убираются сотрудником который исправил все недочёты. Все данные при редактировании заполняются в ручную и хранятся в базе данных

**Comment by V1zefull** [comment]
![image](https://user-images.githubusercontent.com/44523651/198885267-e732fe93-38cb-40f2-9b3a-0c16e8717d2a.png)

Карточка добавления нового тренажёра, в данном случае добавляется эллипсоид все поля вводятся сотрудником и заносятся в базу данных при нажатии на галочку

**Comment by wldmr-key** [comment]
все очень хорошо. Только времени у тебя на все хватит?

**Comment by V1zefull** [comment]
Буду стараться, по идее должно хватить
