### ISSUE TITLE
Прототип приложения

### ISSUE THREAD

**Issue by V1zefull** [V1zefull/Grand-Gym#8]

**Comment by V1zefull** [comment]
Верстка первой страницы закончена всё лежит в ветке master

**Comment by wldmr-key** [comment]
ты считаешь, что для меня посмотреть черновые коды верстки быстрее и приятнее, чем глянуть на картинки? Если да, то ты ошибаешься ))

**Comment by V1zefull** [comment]
Там те же картинки что и скетчи но если надо то буду и сюда грузить то что вышло итоговое в браузере, а исошка скетчей закрытая уже

**Comment by V1zefull** [comment]
![СтраницаHome](https://user-images.githubusercontent.com/44523651/204267348-d96aa2ca-c9bd-444c-bbad-e699bd077175.gif)

Первая страница

**Comment by wldmr-key** [comment]
)) nothing personal
я просто сказал, что запускать твоего клиента, чтобы посмотреть на дизайн я вряд ли буду
Поэтому, если ты хочешь показать и посоветоваться, то имеет смысл сюда постить картинки. Если этот issue чисто для самоорганизации и уведомления меня о прогрессе, то - необязательно

**Comment by V1zefull** [comment]
![СтраницаRegLog](https://user-images.githubusercontent.com/44523651/204267832-482e92bf-da8e-4ca4-bd40-3963338795bd.gif)
Страницы регистрации и логина
